from itertools import groupby

JOB_SCRIPT_TEMPLATE = """#!/bin/bash
#SBATCH -J {Material}_{JobType}
#SBATCH -o job.%j.out
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --time=168:00:00
#SBATCH -p normal

export OMP_NUM_THREADS=1
mpirun -np $SLURM_NTASKS vasp_std > run.log 2>&1
"""

class IncarBuilder:
    def __init__(self):
        self.base_config = {
            "PREC": "Normal",
            "ENCUT": 400,
            "EDIFF": "1.0e-06",
            "ISPIN": 2,
            "ISYM": 0,
            "NCORE": 2,
            "LREAL": "Auto",
            "ALGO": "Fast"
        }

    def format_magmom(self, structure_info):
        """
        Generates Run-Length Encoded MAGMOM string (e.g., '8*4.0 8*0.6')
        """
        species_list = structure_info.get('species', [])
        
        if not species_list:
            return structure_info.get('magmom', '') # Fallback

        # Heuristic assignment
        raw_moments = []
        tm_set = {"Sc","Ti","V","Cr","Mn","Fe","Co","Ni","Cu","Zn",
                  "Y","Zr","Nb","Mo","Tc","Ru","Rh","Pd","Ag","Cd",
                  "Hf","Ta","W","Re","Os","Ir","Pt","Au","Hg"}
        
        for sp in species_list:
             el = "".join([c for c in sp if c.isalpha()]) # Remove oxidation state numbers if any
             if el in tm_set:
                 raw_moments.append(4.0) # High spin default
             else:
                 raw_moments.append(0.6)

        parts = []
        for val, group in groupby(raw_moments):
            count = sum(1 for _ in group)
            parts.append(f"{count}*{val}")
            
        return " ".join(parts)

    def generate_incar(self, settings, structure_info):
        """
        Generates INCAR string based on settings and structure info.
        """
        job_type = settings.get('job_type', 'static')
        is_metal = settings.get('is_metal', False)
        use_dft_u = settings.get('use_dft_u', False)
        
        # Start with base
        incar = self.base_config.copy()
        incar['SYSTEM'] = f"{structure_info.get('formula', 'System')} {job_type.capitalize()}"
        
        # MAGMOM RLE
        incar['MAGMOM'] = self.format_magmom(structure_info)

        # Job Type Specifics
        if job_type == 'relaxation':
            incar.update({
                "IBRION": 2,
                "NSW": 50,
                "ISIF": 3,
                "EDIFFG": -0.01,
                "LWAVE": ".FALSE.",
                "LCHARG": ".FALSE."
            })
        elif job_type == 'static':
            incar.update({
                "IBRION": -1,
                "NSW": 0,
                "LWAVE": ".TRUE.",
                "LCHARG": ".TRUE.",
                "ALGO": "Normal", 
                "LREAL": ".FALSE."
            })
        elif job_type == 'bands':
            incar.update({
                "IBRION": -1,
                "NSW": 0,
                "ICHARG": 11,
                "LWAVE": ".FALSE.",
                "LCHARG": ".FALSE.",
                "ALGO": "Normal",
                "LREAL": ".FALSE."
            })

        # Logic Rule 1: Smearing
        if is_metal:
            incar['ISMEAR'] = 1
            incar['SIGMA'] = 0.2
        else:
            if job_type == 'static':
                incar['ISMEAR'] = -5 # Tetrahedron
            else:
                incar['ISMEAR'] = 0  # Gaussian
                incar['SIGMA'] = 0.05

        # Logic Rule 2: DFT+U
        if use_dft_u:
            incar['LDAU'] = ".TRUE."
            incar['LDAUTYPE'] = 2
            incar['LMAXMIX'] = 4
            
        # Logic Rule 3: Precision (LREAL)
        num_atoms = structure_info.get('num_atoms', 100)
        if num_atoms < 10:
             incar['LREAL'] = ".FALSE."

        # Apply Overrides
        overrides = settings.get('incar_overrides', {})
        incar.update(overrides)

        # Build String
        out = []
        out.append(f"# --- Generated by IncarBuilder for {job_type} ---")
        for k, v in incar.items():
            if v:
                out.append(f"{k:<8} = {v}")
        
        return "\n".join(out)
